In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('http://stepik.org/media/attachments/course/4852/algae.csv')

In [35]:
df.head()

species       genus  group   sucrose    alanin   citrate   
0    Fucus_vesiculosus       Fucus  brown  3.001472  3.711498  5.004262  \
1  Saccharina_japonica  Saccharina  brown  6.731070  1.255251  5.621499   
2       Fucus_serratus       Fucus  brown  3.276870  0.346431  1.216767   
3      Fucus_distichus       Fucus  brown  6.786996  6.641303  6.423606   
4    Cladophora_fracta  Cladophora  green  3.861470  1.648450  6.940588   

    glucose  oleic_acid  
0  2.548459    6.405165  
1  6.013219    4.156700  
2  3.623225    0.304573  
3  2.272724    3.393203  
4  2.316955    2.528886

##### Число видов бурых, зелёных и красных водорослей

In [69]:
df.groupby('group').agg({'genus': 'count'}).values

array([[6],
       [3],
       [1]], dtype=int64)

##### Дисперсия концентрации цитрата в бурых, зелёных и красных водорослях

###### Сложный вариант:

In [44]:
pow(df.groupby('group').agg({'citrate': 'std'}).values, 2)

array([[5.46894219],
       [3.95011276],
       [       nan]])

###### Простой вариант:

In [68]:
df.groupby('group').agg({'citrate': 'var'}).values.round(2)

array([[5.47],
       [3.95],
       [ nan]])

##### Размах (максимум - минимум) сахарозы в бурых, зелёных и красных водорослях

##### Через aggregate:

In [66]:
df.groupby('group').agg({'sucrose': lambda x: x.max() - x.min()}).values.round(2)

array([[5.19],
       [3.26],
       [0.  ]])

In [93]:
df.groupby('group').agg({'sucrose': np.ptp}).values.round(2)

array([[5.19],
       [3.26],
       [0.  ]])

##### Через apply:

In [67]:
df.groupby('group')['sucrose'].apply(lambda x: x.max() - x.min()).values.round(2)

array([5.19, 3.26, 0.  ])

In [94]:
df.groupby('group')['sucrose'].apply(np.ptp).values.round(2)

array([5.19, 3.26, 0.  ])

#### Рассчет всех показателей одновременно

In [90]:
df.groupby('group').agg({'citrate': 'var', 'sucrose': np.ptp, 'species': 'nunique'}).round(2).values

array([[5.47, 5.19, 6.  ],
       [3.95, 3.26, 3.  ],
       [ nan, 0.  , 1.  ]])