In [50]:
import pandas as pd
import numpy as np

In [2]:
concentrations = pd.read_csv('http://stepik.org/media/attachments/course/4852/algae.csv')

In [3]:
concentrations.head()

species       genus  group   sucrose    alanin   citrate   
0    Fucus_vesiculosus       Fucus  brown  3.001472  3.711498  5.004262  \
1  Saccharina_japonica  Saccharina  brown  6.731070  1.255251  5.621499   
2       Fucus_serratus       Fucus  brown  3.276870  0.346431  1.216767   
3      Fucus_distichus       Fucus  brown  6.786996  6.641303  6.423606   
4    Cladophora_fracta  Cladophora  green  3.861470  1.648450  6.940588   

    glucose  oleic_acid  
0  2.548459    6.405165  
1  6.013219    4.156700  
2  3.623225    0.304573  
3  2.272724    3.393203  
4  2.316955    2.528886

In [99]:
concentrations.groupby('genus').agg({'alanin': ['min', 'mean', 'max']}).loc['Fucus'].values.round(2)

array([0.35, 3.57, 6.64])

In [52]:
np.around(concentrations.query('genus == "Fucus"')['alanin'].describe().loc[['min', 'mean', 'max']].values, decimals=2)

array([0.35, 3.57, 6.64])

In [59]:
concentrations.groupby('genus').agg({'alanin': ['min', 'mean', 'max']}).loc['Fucus'].round(2)

alanin  min     0.35
        mean    3.57
        max     6.64
Name: Fucus, dtype: float64

In [89]:
concentrations.loc[concentrations['genus'] == 'Fucus', 'alanin'].agg(['min', 'mean', 'max']).values.round(2)

array([0.35, 3.57, 6.64])